### ISSUE TITLE
fail to syllabify 'engraved'

### ISSUE THREAD

**Issue by alephpi** [cainesap/syllabify#1]
Hello, thank you for the useful tools.
However, when I run
```
python3 syllabify engraved
```
An error occurs
```
Traceback (most recent call last):
  File "syllable3.py", line 366, in <module>
    for syll in syllable:
  File "syllable3.py", line 169, in factory
    syllable_list = functools.reduce(syllable_fact, cluster_list, [Syllable()])
  File "syllable3.py", line 65, in syllable_fact
    syllable = syllable_list.pop()
AttributeError: 'NoneType' object has no attribute 'pop'
```
Could you verify and debug this problem?

**Comment by alephpi** [comment]
Another finding: engraved can be syllabified by the python2 version. Maybe something to do with your adaptation.
